---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-ddc1090c6e877d332580dadd0128c52a
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/GunSik2/podinfo-deploy.git
